# Generated by Django 5.1.5 on 2025-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('tag', models.CharField(choices=[('Top Sale Watches', 'Top Sale Watches'), ('Feature Watches', 'Feature Watches'), ('New Arrivals', 'New Arrivals')], max_length=150)),
            ],
        ),
    ]
